version: '3.7'

services:
  app:
    image: registry.communicatio.com/ikusei/smart-village-app-converter-json2graphql
    depends_on: [db]
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    configs:
      - source: smart-village-app-converter-json2graphql-database-yml
        target: /app/config/database.yml
      - source: smart-village-app-converter-json2graphql-unicorn-rb
        target: /app/config/unicorn.rb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - unicorn:/unicorn
      - assets:/assets
    deploy:
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx
    depends_on: [app]
    networks: [default, public]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - unicorn:/unicorn
      - assets:/public
    labels:
      - traefik.docker.network=public
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: postgres
    environment:
      POSTGRES_USER: smart
      POSTGRES_PASSWORT: smart
      POSTGRES_DB: smart
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - db:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  db:
  unicorn:
  assets:

configs:
  smart-village-app-converter-json2graphql-nginx-conf:
    external: true
  smart-village-app-converter-json2graphql-database-yml:
    external: true
  smart-village-app-converter-json2graphql-unicorn-rb:
    external: true

networks:
  public:
    external: true
